import { useEffect, useRef, useState, type DragEvent, type FormEvent } from 'react';
import { Download, ExternalLink, File, FileImage, FileText, Pencil, Search, Trash2, UploadCloud, X } from 'lucide-react';
import { api } from '../services/api';
import type { ConfigurationData, Dashboard, StoredFile } from '../types';
import { Badge, Card, Empty } from '../components/UI';
import { Field, Modal } from '../components/Modal';
import { Page } from './Resources';
import { fileTypeLabel, formatFileSize } from '../utils/files';

const categories=['Allgemein','Arbeitsblatt','Lernzettel','Unterricht','Prüfung','Dokumentation'];
export function FilesPage({data}:{data:Dashboard}){
  const [files,setFiles]=useState<StoredFile[]>([]),[config,setConfig]=useState<ConfigurationData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[uploadOpen,setUploadOpen]=useState(false),[edit,setEdit]=useState<StoredFile|null>(null),[filters,setFilters]=useState({q:'',subject_id:'',learning_field_id:'',topic_id:'',category:'',mime_type:''});
  async function load(){setLoading(true);try{const q=new URLSearchParams(Object.entries(filters).filter(([,value])=>Boolean(value)) as Array<[string,string]>).toString();const [f,c]=await Promise.all([api.files(q),config?Promise.resolve(config):api.configuration()]);setFiles(f);setConfig(c);setError('')}catch(e){setError(e instanceof Error?e.message:'Dateien konnten nicht geladen werden.')}finally{setLoading(false)}}
  useEffect(()=>{const timer=setTimeout(load,filters.q?250:0);return()=>clearTimeout(timer)},[filters]);
  async function remove(file:StoredFile){if(confirm(`„${file.original_name}“ wirklich dauerhaft löschen?`)){try{await api.remove('files',file.id);await load()}catch(e){alert(e instanceof Error?e.message:'Löschen fehlgeschlagen.')}}}
  const set=(key:string,value:string)=>setFilters(v=>({...v,[key]:value}));
  return <Page title="Dateien" subtitle="Unterlagen sicher in Cloudflare R2 speichern und Lerninhalten zuordnen" action="Datei hochladen" onAction={()=>setUploadOpen(true)}>
    <Card className="file-filters"><div className="search-inline"><Search/><input aria-label="Dateien suchen" placeholder="Dateiname durchsuchen …" value={filters.q} onChange={e=>set('q',e.target.value)}/></div><select aria-label="Fach filtern" value={filters.subject_id} onChange={e=>set('subject_id',e.target.value)}><option value="">Alle Fächer</option>{config?.subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><select aria-label="Lernfeld filtern" value={filters.learning_field_id} onChange={e=>set('learning_field_id',e.target.value)}><option value="">Alle Lernfelder</option>{config?.learningFields.map(l=><option value={l.id} key={l.id}>{l.code} – {l.name}</option>)}</select><select aria-label="Thema filtern" value={filters.topic_id} onChange={e=>set('topic_id',e.target.value)}><option value="">Alle Themen</option>{data.topics.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select><select aria-label="Kategorie filtern" value={filters.category} onChange={e=>set('category',e.target.value)}><option value="">Alle Kategorien</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Dateityp filtern" value={filters.mime_type} onChange={e=>set('mime_type',e.target.value)}><option value="">Alle Dateitypen</option><option value="application/pdf">PDF</option><option value="image/png">PNG</option><option value="image/jpeg">JPEG</option><option value="application/vnd.openxmlformats-officedocument.wordprocessingml.document">DOCX</option><option value="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">XLSX</option><option value="application/vnd.openxmlformats-officedocument.presentationml.presentation">PPTX</option><option value="text/plain">Text</option><option value="text/markdown">Markdown</option></select></Card>
    {error&&<p className="error">{error}</p>}{loading?<Card><p>Lade Dateien …</p></Card>:files.length?<div className="file-list">{files.map(file=><Card key={file.id} className="file-row"><FileIcon type={file.mime_type}/><div className="grow"><b>{file.original_name}</b><div className="file-meta"><span>{fileTypeLabel(file.mime_type)}</span><span>{formatFileSize(file.size)}</span><span>{new Date(file.created_at).toLocaleDateString('de-DE')}</span></div><div className="file-links">{file.subject_name&&<Badge>{file.subject_name}</Badge>}{file.learning_field_code&&<Badge>{file.learning_field_code}</Badge>}{file.topic_name&&<Badge>{file.topic_name}</Badge>}<Badge>{file.category}</Badge></div></div><div className="row-actions"><a className="icon" href={`/api/files/${file.id}/content`} target="_blank" rel="noreferrer" aria-label="Öffnen"><ExternalLink/></a><a className="icon" href={`/api/files/${file.id}/content?download=1`} download={file.original_name} aria-label="Herunterladen"><Download/></a><button className="icon" onClick={()=>setEdit(file)} aria-label="Metadaten bearbeiten"><Pencil/></button><button className="icon danger" onClick={()=>remove(file)} aria-label="Datei löschen"><Trash2/></button></div></Card>)}</div>:<Card><Empty title="Noch keine Dateien hochgeladen" action={<button className="primary" onClick={()=>setUploadOpen(true)}><UploadCloud/> Erste Datei hochladen</button>}/></Card>}
    {uploadOpen&&config&&<UploadModal config={config} topics={data.topics} onClose={()=>setUploadOpen(false)} onDone={async()=>{setUploadOpen(false);await load()}}/>}
    {edit&&config&&<MetadataModal file={edit} config={config} topics={data.topics} onClose={()=>setEdit(null)} onDone={async()=>{setEdit(null);await load()}}/>}
  </Page>
}
function UploadModal({config,topics,onClose,onDone}:{config:ConfigurationData;topics:Dashboard['topics'];onClose:()=>void;onDone:()=>void}){const [file,setFile]=useState<File|null>(null),[drag,setDrag]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),input=useRef<HTMLInputElement>(null);function drop(e:DragEvent){e.preventDefault();setDrag(false);const f=e.dataTransfer.files[0];if(f)setFile(f)}function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!file)return setError('Bitte wähle eine Datei aus.');const form=new FormData(e.currentTarget);form.set('file',file);const xhr=new XMLHttpRequest();xhr.open('POST','/api/files');xhr.upload.onprogress=event=>event.lengthComputable&&setProgress(Math.round(event.loaded/event.total*100));xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)onDone();else{try{setError(JSON.parse(xhr.responseText).error)}catch{setError('Upload fehlgeschlagen.')}}};xhr.onerror=()=>setError('Die Datei konnte nicht hochgeladen werden.');xhr.send(form)}return <Modal title="Datei hochladen" onClose={onClose}><form onSubmit={submit} className="form"><div className={`dropzone ${drag?'drag':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop} onClick={()=>input.current?.click()}><input ref={input} hidden type="file" accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx,.pptx,.txt,.md" onChange={e=>setFile(e.target.files?.[0]||null)}/><UploadCloud/>{file?<><b>{file.name}</b><span>{fileTypeLabel(file.type)} · {formatFileSize(file.size)}</span></>:<><b>Datei hier ablegen</b><span>oder zum Auswählen klicken · maximal 20 MB</span></>}</div><MetadataFields config={config} topics={topics}/>{progress>0&&<div className="upload-progress"><span style={{width:`${progress}%`}}/><b>{progress}%</b></div>}{error&&<p className="error">{error}</p>}<button className="primary" disabled={!file||progress>0&&progress<100}>Hochladen</button></form></Modal>}
function MetadataModal({file,config,topics,onClose,onDone}:{file:StoredFile;config:ConfigurationData;topics:Dashboard['topics'];onClose:()=>void;onDone:()=>void}){const [error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api.updateFile(file.id,Object.fromEntries(new FormData(e.currentTarget)));onDone()}catch(err){setError(err instanceof Error?err.message:'Speichern fehlgeschlagen.')}}return <Modal title="Datei bearbeiten" onClose={onClose}><form className="form" onSubmit={submit}><p><b>{file.original_name}</b><br/><small>{formatFileSize(file.size)} · {fileTypeLabel(file.mime_type)}</small></p><MetadataFields config={config} topics={topics} value={file}/>{error&&<p className="error">{error}</p>}<button className="primary">Änderungen speichern</button></form></Modal>}
function MetadataFields({config,topics,value}:{config:ConfigurationData;topics:Dashboard['topics'];value?:StoredFile}){return <><Field label="Fach"><select name="subject_id" defaultValue={value?.subject_id||''}><option value="">Kein Fach</option>{config.subjects.filter((s:any)=>s.active!==0).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><Field label="Lernfeld"><select name="learning_field_id" defaultValue={value?.learning_field_id||''}><option value="">Kein Lernfeld</option>{config.learningFields.filter(l=>l.status==='active').map(l=><option value={l.id} key={l.id}>{l.code} – {l.name}</option>)}</select></Field><Field label="Thema"><select name="topic_id" defaultValue={value?.topic_id||''}><option value="">Kein Thema</option>{topics.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></Field><Field label="Kategorie"><select name="category" defaultValue={value?.category||'Allgemein'}>{categories.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Beschreibung"><textarea name="description" defaultValue={value?.description}/></Field></>}
function FileIcon({type}:{type:string}){return <div className={`file-icon ${type.startsWith('image/')?'image':''}`}>{type.startsWith('image/')?<FileImage/>:type==='application/pdf'?<FileText/>:<File/>}</div>}
