import {Hono} from 'hono';import {z} from 'zod';
type Bindings={DB:D1Database;FILES:R2Bucket;ASSETS:Fetcher;APP_ENV:string};const app=new Hono<{Bindings:Bindings}>();
const resources={subjects:['name','color','description'],topics:['subject_id','title','status','description'],tasks:['title','description','due_date','priority','status','category','subject_id','topic_id'],notes:['title','content','topic_id','favorite'],events:['title','event_date','type','subject_id','topic_id'],flashcards:['topic_id','question','answer','difficulty','tags'],grades:['subject_id','name','date','grade','weight','comment'],departments:['name','start_date','end_date','description','technologies','contact'],activities:['department_id','topic_id','activity_date','title','description','programs','duration_minutes'],lessons:['subject_id','topic_id','lesson_date','title','notes','homework'],training_entries:['week_id','weekday','entry_type','content','minutes']} as const;type Resource=keyof typeof resources;
const safe=(v:unknown)=>v===''?null:v;function isResource(x:string):x is Resource{return x in resources}
app.use('/api/*',async(c,next)=>{try{await next()}catch(e){console.error(e);return c.json({error:'Die Anfrage konnte nicht verarbeitet werden. Bitte versuche es erneut.'},500)}});
app.get('/api/dashboard',async c=>{const names=['subjects','topics','tasks','notes','events','flashcards','grades','departments','activities','lessons','training_entries'] as const;const out:Record<string,unknown>={};await Promise.all(names.map(async n=>{out[n]=(await c.env.DB.prepare(`SELECT * FROM ${n} ORDER BY ${n==='tasks'?'due_date':n==='events'?'event_date':'id'} ${n==='notes'?'DESC':'ASC'}`).all()).results}));return c.json({subjects:out.subjects,topics:out.topics,tasks:out.tasks,notes:out.notes,events:out.events,flashcards:out.flashcards,grades:out.grades,departments:out.departments,activities:out.activities,lessons:out.lessons,trainingEntries:out.training_entries})});
app.post('/api/files',async c=>{const form=await c.req.formData(),file=form.get('file');if(!(file instanceof File)||file.size>10*1024*1024)return c.json({error:'Bitte wähle eine Datei bis maximal 10 MB.'},400);const allowed=['application/pdf','image/png','image/jpeg','text/plain','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation'];if(!allowed.includes(file.type))return c.json({error:'Dieser Dateityp wird nicht unterstützt.'},400);const key=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await c.env.FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type}});return c.json({key,name:file.name},201)});
app.post('/api/:resource',async c=>{const r=c.req.param('resource');if(!isResource(r))return c.json({error:'Unbekannter Bereich'},404);const body=await c.req.json<Record<string,unknown>>();const fields=resources[r].filter(f=>body[f]!==undefined);if(!fields.length)return c.json({error:'Bitte fülle die Pflichtfelder aus.'},400);const required=r==='subjects'?'name':r==='topics'?'title':r==='tasks'?'title':r==='notes'?'title':r==='events'?'title':r==='flashcards'?'question':'name';if(required in body&&typeof body[required]==='string'){const valid=z.string().trim().min(1).max(500).safeParse(body[required]);if(!valid.success)return c.json({error:'Bitte gib einen gültigen Wert ein.'},400)}const vals=fields.map(f=>safe(body[f]));const marks=fields.map(()=>'?').join(',');const result=await c.env.DB.prepare(`INSERT INTO ${r} (${fields.join(',')}) VALUES (${marks})`).bind(...vals).run();const row=await c.env.DB.prepare(`SELECT * FROM ${r} WHERE id=?`).bind(result.meta.last_row_id).first();return c.json(row,201)});
app.put('/api/:resource/:id',async c=>{const r=c.req.param('resource');if(!isResource(r))return c.json({error:'Unbekannter Bereich'},404);const id=Number(c.req.param('id'));const body=await c.req.json<Record<string,unknown>>();const fields=resources[r].filter(f=>body[f]!==undefined);if(!Number.isInteger(id)||!fields.length)return c.json({error:'Ungültige Eingabe'},400);await c.env.DB.prepare(`UPDATE ${r} SET ${fields.map(f=>`${f}=?`).join(',')}, updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(...fields.map(f=>safe(body[f])),id).run();return c.json(await c.env.DB.prepare(`SELECT * FROM ${r} WHERE id=?`).bind(id).first())});
app.delete('/api/:resource/:id',async c=>{const r=c.req.param('resource');if(!isResource(r))return c.json({error:'Unbekannter Bereich'},404);await c.env.DB.prepare(`DELETE FROM ${r} WHERE id=?`).bind(Number(c.req.param('id'))).run();return c.json({ok:true})});
app.get('/api/search',async c=>{const q=`%${(c.req.query('q')||'').slice(0,100)}%`;const query=(table:string,cols:string)=>c.env.DB.prepare(`SELECT * FROM ${table} WHERE ${cols.split(',').map(x=>`${x} LIKE ?`).join(' OR ')} LIMIT 10`).bind(...cols.split(',').map(()=>q)).all().then(x=>x.results);const [topics,notes,tasks,flashcards,events,lessons]=await Promise.all([query('topics','title,description'),query('notes','title,content'),query('tasks','title,description'),query('flashcards','question,answer'),query('events','title,type'),query('lessons','title,notes')]);return c.json({Themen:topics,Lernzettel:notes,Aufgaben:tasks,Karteikarten:flashcards,Termine:events,Unterricht:lessons})});
app.get('/api/export',async c=>{const out:Record<string,unknown>={exportedAt:new Date().toISOString(),version:1};for(const name of Object.keys(resources)){out[name]=(await c.env.DB.prepare(`SELECT * FROM ${name}`).all()).results}return c.json(out)});
export default app;
